name: CI Build
on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - "**"
      # - main
      # - master
      # - trunk
    tags:
      - "!**"
  # Run every time a PR is updated
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      - id: setup-bun
        name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - id: install-deps
        name: Install dependencies
        run: |
          bun install
      - id: test
        name: Run tests
        run: |
          bun test
