name: Commit Lint
on:
  pull_request:
    branches:
      - main
      - master
      - trunk
jobs:
  conventions:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Code
      - uses: webiny/action-conventional-commits@v1.3.0
        name: Validate Commits
        # optional, required for private repos:
        # with:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}